version: '3.8'

services:
  samloc-scorekeeper:
    build:
      context: .
      args:
        - VITE_API_URL=${VITE_API_URL}
    container_name: samloc-app
    restart: unless-stopped
    ports:
      - "3001:3001"
    environment:
      - PORT=3001
      - DATA_DIR=/data/samloc
      - NODE_ENV=production
    volumes:
      - ./server/data:/data/samloc
    networks:
      - proxy

networks:
  proxy:
    external: true
